/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utiles;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JPanel;

/**
 *
 * @author karlagutz
 */
public class PanelCrear extends JPanel {
    Boolean paintCirculo = false;
    Boolean paintCuadrado = false;
    Boolean paintGrises = false;
    Boolean paintColores = false;
    /**
     * Creates new form PanelCrear
     */
    public PanelCrear() {
        initComponents();
    }
    
    public void drawCircle( Boolean draw ) {
       paintCirculo = true;
       repaint();
    }
    
    @Override
    protected void paintComponent( Graphics g ) {
      super.paintComponent(g);
      
       if ( paintCirculo ) {
          g.setColor(Color.BLUE);
          g.fillOval(1, 1, 200, 200);
          
       } else if (paintCuadrado) {
            g.setColor(Color.red);
            g.fillRect(20, 20, 200, 200);
        }
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
